# Generated by Django 4.0.7 on 2023-09-14 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MLModelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelType', models.CharField(choices=[('Linear Classification', 'Linear Classification'), ('Linear Regression', 'Linear Regression'), ('Decision Tree Classifier', 'Decision Tree Classifier'), ('Decision Tree Regressor', 'Decision Tree Regressor'), ('Random Forest Classifier', 'Random Forest Classifier'), ('Random Forest Regressor', 'Random Forest Regressor')], max_length=32)),
            ],
        ),
    ]
