# Generated by Django 4.0.7 on 2023-09-14 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mlmodeldata',
            old_name='modelType',
            new_name='model_type',
        ),
        migrations.AddField(
            model_name='mlmodeldata',
            name='best_params_names',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='mlmodeldata',
            name='best_params_values',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='mlmodeldata',
            name='best_test_results',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='mlmodeldata',
            name='best_train_results',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='mlmodeldata',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
