# Generated by Django 4.0.7 on 2023-09-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_mlmodeldata_used_metric_results_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodeldata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
